theme = "horizon-dark"

[editor]
line-number = "relative"
bufferline = "multiple"
shell = ["zsh", "-c"]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"G" = "goto_last_line"
"A-p" = "shrink_selection"
"A-n" = "expand_selection"
"A-l" = "indent"
"A-h" = "unindent"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
J = "copy_selection_on_next_line"
K = "copy_selection_on_prev_line"
V = ["extend_line_below", "select_mode"]
Y = {  Y = ["extend_line_below", "yank"] }
W = ["select_mode", "move_next_word_start"]
B = ["select_mode", "move_prev_word_start"]
E = ["select_mode", "move_next_word_end"]
D = ["select_mode", "goto_line_end", "delete_selection"]
C = ["select_mode", "goto_line_end", "change_selection"]

[keys.normal.space]

[keys.select]
j = "extend_line_below"
k = "extend_line_above"
"A-l" = "indent"
"A-h" = "unindent"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["search_selection", "extend_search_next"]
C-k = ["search_selection", "extend_search_prev"]
";" = ["collapse_selection", "normal_mode"]

[keys.normal.L]
d = "goto_next_diag"
f = "goto_next_function"
a = "goto_next_parameter"
c = "goto_next_comment"
p = "goto_next_paragraph"
t = "goto_next_class"
l = "select_next_sibling"
L = "ensure_selections_forward"


[keys.normal.H]
d = "goto_prev_diag"
f = "goto_prev_function"
a = "goto_prev_parameter"
c = "goto_prev_comment"
p = "goto_prev_paragraph"
t = "goto_prev_class"
h = "select_prev_sibling"
H = "flip_selections"

[keys.select.H]
H = "flip_selections"

[keys.select.L]
L = "ensure_selections_forward"
