theme = "dark_plus"

[editor]
line-number = "relative"
bufferline = "multiple"
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
"C-c" = ["collapse_selection", "keep_primary_selection"]
"G" = "goto_last_line"
C-j = ["search_selection", "extend_search_next"]
C-k = ["search_selection", "extend_search_prev"]

[keys.select]
"C-c" = "normal_mode"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"
